### PR TITLE
fix: sigstore cache dir error

### LINKED ISSUE #736: Error: No such file or directory (os error 2) when starting PolicyServer
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

After merging sigstore related fixes, we have Error: No such file or directory (os error 2).
This is caused by the sigstore cache directory not being found, see https://github.com/kubewarden/policy-server/blob/30c2cdb7efec01201342aa41579296b8bccbad29/src/lib.rs#L66

### Expected Behavior

_No response_

### Steps To Reproduce

Start the latest policy server 

### Environment

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by fabriziosestito**
## Description

Fixes #736 

## Additional Information

`PolicyDownloader` was refactored so that we initialize the `ManualTrustRoot` just once and pass it to the constructor.

### CODE REVIEW

File: src/policy_downloader.rs [hunk 1]
```diff
@@ -340,8 +314,31 @@ mod tests {
...
+        let manual_root = ManualTrustRoot {
+            fulcio_certs: Some(fulcio_certs),
+            rekor_keys: Some(
+                repo.rekor_keys()
+                    .expect("Cannot fetch Rekor keys from TUF repository")
+                    .iter()
+                    .map(|k| k.to_vec())
+                    .collect(),
+            ),
+        };
```
Comment (fabriziosestito) [inline src/policy_downloader.rs:337]: we do the same in the PolicyServer constructor, should we create a utility function in another module?

Comment (viccuad) [reply src/policy_downloader.rs:337]: I'm ok with not doing it, the upstream types and functions are bound to scream at us if there's a change, and there is no logic.

**Review by viccuad — APPROVED** [review]
LGTM. Maybe a test for `new_from_config()` would be good, but mocking it seems quite complicated for essentially testing only that the dir is created and populated if it didn't exist.

File: src/policy_downloader.rs (hunk 1 above)
Comment (flavio) [reply src/policy_downloader.rs:337]: I would leave it as it currently is, I agree with @viccuad

**Review by flavio — APPROVED** [review]
@fabriziosestito thanks a lot for having fixed it! :heart:

**Comment by fabriziosestito** [comment]
> LGTM. Maybe a test for `new_from_config()` would be good, but mocking it seems quite complicated for essentially testing only that the dir is created and populated if it didn't exist.

@viccuad we are testing `new_from_config` indirectly in the integration tests, maybe we could extend those tests with a signed policy. Since we test `PolicyDownloader` in isolation, they will be redundant, so I am not sure it is worth it.
